### ISSUE TITLE
SUBMITボタン押下後に砂時計を表示させたい

### ISSUE THREAD

**Issue by siida36** [asaka2-alb/smart-sauna-map-front#24]
SUBMITボタン押下後のレスポンスが戻ってくるまでにタイムラグがあり、現状では押下したのかどうかがわからない。

そのため砂時計を表示するなどして、リクエストを投げた状態であることを明示したい。

**Comment by taisei-watanabe** [comment]
## 案1

### 概要

- [こちらのページ](https://sauna-ikitai.com/search?prefecture%5B%5D=shizuoka&ordering=ikitai_counts_desc)を開いた際に描画されるロウリュのアニメーションのように、半透明のレイヤで暗転？させた上で、アニメーション（or 画像）を表示させる。

### 実現手段

TBD.

## 案2

### 概要

- 「SUBMIT」ボタンの中身をぐるぐる回すなどして、待機状態だとわかるようにする。

### 実現手段

TBD.
