### ISSUE TITLE
infoWindowの水温などの情報をより伝わるデザインにする

### ISSUE THREAD

**Issue by siida36** [asaka2-alb/smart-sauna-map-front#27]
## 問題

現状では「男; サ: xxx 水: xxx」となっていていまいち伝わりづらい。

<img width="419" alt="スクリーンショット 2022-10-19 9 41 39" src="https://user-images.githubusercontent.com/36360393/196570943-6c2d2141-d310-429c-970c-8aa47480b8de.png">

## 提案

温度であることがわかりやすくする？
男・女で色を変える？

**Comment by taisei-watanabe** [comment]
- ついでに特定のサウナクリックすると落ちるバグを治す
